# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f1 <- function(x, resSq, n) {
    .Call('_FarmTest_f1', PACKAGE = 'FarmTest', x, resSq, n)
}

rootf1 <- function(resSq, n, low, up, tol = 0.0001, maxIte = 500L) {
    .Call('_FarmTest_rootf1', PACKAGE = 'FarmTest', resSq, n, low, up, tol, maxIte)
}

f2 <- function(x, resSq, n, d, N) {
    .Call('_FarmTest_f2', PACKAGE = 'FarmTest', x, resSq, n, d, N)
}

rootf2 <- function(resSq, n, d, N, low, up, tol = 0.0001, maxIte = 500L) {
    .Call('_FarmTest_rootf2', PACKAGE = 'FarmTest', resSq, n, d, N, low, up, tol, maxIte)
}

huberMean <- function(X, n, epsilon = 0.0001, iteMax = 500L) {
    .Call('_FarmTest_huberMean', PACKAGE = 'FarmTest', X, n, epsilon, iteMax)
}

huberMeanVec <- function(X, n, p, epsilon = 0.0001, iteMax = 500L) {
    .Call('_FarmTest_huberMeanVec', PACKAGE = 'FarmTest', X, n, p, epsilon, iteMax)
}

hMeanCov <- function(Z, n, d, N, epsilon = 0.0001, iteMax = 500L) {
    .Call('_FarmTest_hMeanCov', PACKAGE = 'FarmTest', Z, n, d, N, epsilon, iteMax)
}

huberCov <- function(X, n, p) {
    .Call('_FarmTest_huberCov', PACKAGE = 'FarmTest', X, n, p)
}

mad <- function(x) {
    .Call('_FarmTest_mad', PACKAGE = 'FarmTest', x)
}

sgn <- function(x) {
    .Call('_FarmTest_sgn', PACKAGE = 'FarmTest', x)
}

standardize <- function(X, mx, sx, p) {
    .Call('_FarmTest_standardize', PACKAGE = 'FarmTest', X, mx, sx, p)
}

updateHuber <- function(Z, res, der, grad, n, tau, n1) {
    invisible(.Call('_FarmTest_updateHuber', PACKAGE = 'FarmTest', Z, res, der, grad, n, tau, n1))
}

huberReg <- function(X, Y, n, p, tol = 0.0001, constTau = 1.345, iteMax = 5000L) {
    .Call('_FarmTest_huberReg', PACKAGE = 'FarmTest', X, Y, n, p, tol, constTau, iteMax)
}

huberRegCoef <- function(X, Y, n, p, tol = 0.0001, constTau = 1.345, iteMax = 5000L) {
    .Call('_FarmTest_huberRegCoef', PACKAGE = 'FarmTest', X, Y, n, p, tol, constTau, iteMax)
}

huberRegItcp <- function(X, Y, n, p, tol = 0.0001, constTau = 1.345, iteMax = 5000L) {
    .Call('_FarmTest_huberRegItcp', PACKAGE = 'FarmTest', X, Y, n, p, tol, constTau, iteMax)
}

getP <- function(T, alternative) {
    .Call('_FarmTest_getP', PACKAGE = 'FarmTest', T, alternative)
}

getPboot <- function(mu, boot, h0, alternative, p, B) {
    .Call('_FarmTest_getPboot', PACKAGE = 'FarmTest', mu, boot, h0, alternative, p, B)
}

adjust <- function(Prob, alpha, p) {
    .Call('_FarmTest_adjust', PACKAGE = 'FarmTest', Prob, alpha, p)
}

getRatio <- function(eigenVal, n, p) {
    .Call('_FarmTest_getRatio', PACKAGE = 'FarmTest', eigenVal, n, p)
}

rmTest <- function(X, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_rmTest', PACKAGE = 'FarmTest', X, h0, alpha, alternative)
}

rmTestBoot <- function(X, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_rmTestBoot', PACKAGE = 'FarmTest', X, h0, alpha, alternative, B)
}

rmTestTwo <- function(X, Y, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_rmTestTwo', PACKAGE = 'FarmTest', X, Y, h0, alpha, alternative)
}

rmTestTwoBoot <- function(X, Y, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_rmTestTwoBoot', PACKAGE = 'FarmTest', X, Y, h0, alpha, alternative, B)
}

farmTest <- function(X, h0, K = -1L, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTest', PACKAGE = 'FarmTest', X, h0, K, alpha, alternative)
}

farmTestTwo <- function(X, Y, h0, KX = -1L, KY = -1L, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTestTwo', PACKAGE = 'FarmTest', X, Y, h0, KX, KY, alpha, alternative)
}

farmTestFac <- function(X, fac, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTestFac', PACKAGE = 'FarmTest', X, fac, h0, alpha, alternative)
}

farmTestFacBoot <- function(X, fac, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_farmTestFacBoot', PACKAGE = 'FarmTest', X, fac, h0, alpha, alternative, B)
}

farmTestTwoFac <- function(X, facX, Y, facY, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTestTwoFac', PACKAGE = 'FarmTest', X, facX, Y, facY, h0, alpha, alternative)
}

farmTestTwoFacBoot <- function(X, facX, Y, facY, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_farmTestTwoFacBoot', PACKAGE = 'FarmTest', X, facX, Y, facY, h0, alpha, alternative, B)
}

