# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

huberMean <- function(X, n, epsilon = 0.0001, iteMax = 500L) {
    .Call('_FarmTest_huberMean', PACKAGE = 'FarmTest', X, n, epsilon, iteMax)
}

huberCov <- function(X, n, p) {
    .Call('_FarmTest_huberCov', PACKAGE = 'FarmTest', X, n, p)
}

huberReg <- function(X, Y, n, p, tol = 0.0000001, constTau = 1.345, iteMax = 5000L) {
    .Call('_FarmTest_huberReg', PACKAGE = 'FarmTest', X, Y, n, p, tol, constTau, iteMax)
}

getRej <- function(Prob, alpha, p) {
    .Call('_FarmTest_getRej', PACKAGE = 'FarmTest', Prob, alpha, p)
}

rmTest <- function(X, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_rmTest', PACKAGE = 'FarmTest', X, h0, alpha, alternative)
}

rmTestBoot <- function(X, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_rmTestBoot', PACKAGE = 'FarmTest', X, h0, alpha, alternative, B)
}

rmTestTwo <- function(X, Y, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_rmTestTwo', PACKAGE = 'FarmTest', X, Y, h0, alpha, alternative)
}

rmTestTwoBoot <- function(X, Y, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_rmTestTwoBoot', PACKAGE = 'FarmTest', X, Y, h0, alpha, alternative, B)
}

farmTest <- function(X, h0, K = -1L, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTest', PACKAGE = 'FarmTest', X, h0, K, alpha, alternative)
}

farmTestTwo <- function(X, Y, h0, KX = -1L, KY = -1L, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTestTwo', PACKAGE = 'FarmTest', X, Y, h0, KX, KY, alpha, alternative)
}

farmTestFac <- function(X, fac, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTestFac', PACKAGE = 'FarmTest', X, fac, h0, alpha, alternative)
}

farmTestFacBoot <- function(X, fac, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_farmTestFacBoot', PACKAGE = 'FarmTest', X, fac, h0, alpha, alternative, B)
}

farmTestTwoFac <- function(X, facX, Y, facY, h0, alpha = 0.05, alternative = "two.sided") {
    .Call('_FarmTest_farmTestTwoFac', PACKAGE = 'FarmTest', X, facX, Y, facY, h0, alpha, alternative)
}

farmTestTwoFacBoot <- function(X, facX, Y, facY, h0, alpha = 0.05, alternative = "two.sided", B = 500L) {
    .Call('_FarmTest_farmTestTwoFacBoot', PACKAGE = 'FarmTest', X, facX, Y, facY, h0, alpha, alternative, B)
}

